#!/bin/bash
# Scaffold a new provider adapter package.
# Usage: new-provider.sh <name>
# Example: new-provider.sh perplexity → packages/provider-perplexity/

set -euo pipefail

NAME="${1:?Usage: new-provider.sh <name>}"

# Validate name: lowercase alphanumeric and hyphens only
if [[ ! "$NAME" =~ ^[a-z][a-z0-9-]*$ ]]; then
  echo "Error: name must be lowercase alphanumeric with hyphens (e.g. 'perplexity', 'open-router')" >&2
  exit 1
fi

ROOT=$(git rev-parse --show-toplevel)
PKG_DIR="$ROOT/packages/provider-${NAME}"

if [ -d "$PKG_DIR" ]; then
  echo "Error: $PKG_DIR already exists" >&2
  exit 1
fi

# Convert kebab-case name to PascalCase (e.g. "open-router" → "OpenRouter")
PASCAL=$(echo "$NAME" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)} 1' | sed 's/ //g')

echo "Scaffolding @os/provider-${NAME} (${PASCAL})..."

mkdir -p "$PKG_DIR/src/__fixtures__"
touch "$PKG_DIR/src/__fixtures__/.gitkeep"

# Helper: pipe a single-quoted heredoc through sed to replace placeholders.
# Single-quoted heredoc delimiters prevent shell expansion of backticks and $,
# so JS template literals pass through verbatim.
apply_template() {
  sed "s/__NAME__/${NAME}/g; s/__PASCAL__/${PASCAL}/g" > "$1"
}

# ---------------------------------------------------------------------------
# package.json — mirrors existing provider adapter packages exactly
# ---------------------------------------------------------------------------
cat > "$PKG_DIR/package.json" << ENDJSON
{
  "name": "@os/provider-${NAME}",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "sideEffects": false,
  "main": "./dist/index.js",
  "module": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": "./src/index.ts",
    "./package.json": "./package.json"
  },
  "publishConfig": {
    "exports": {
      ".": "./dist/index.js",
      "./package.json": "./package.json"
    }
  },
  "scripts": {
    "dev": "pnpm run build:watch",
    "clean": "rm -rf ./dist",
    "type": "tsc --noEmit",
    "type:watch": "tsc --noEmit --watch",
    "lint": "run-s lint:eslint lint:prettier",
    "lint:eslint": "eslint --fix",
    "lint:prettier": "prettier -luv '*.{md,mdx,html,xml,svg}'",
    "test": "vitest run --passWithNoTests",
    "test:watch": "vitest",
    "build": "tsdown --config-loader=unrun",
    "build:watch": "tsdown --config-loader=unrun --watch"
  },
  "dependencies": {
    "@os/core": "workspace:*",
    "@os/errors": "workspace:*",
    "@os/provider": "workspace:*"
  },
  "devDependencies": {
    "@os/browserslist-config": "workspace:*",
    "@os/eslint-config": "workspace:*",
    "@os/prettier-config": "workspace:*",
    "@os/tsconfig": "workspace:*",
    "@os/tsdown-config": "workspace:*",
    "@os/vite-config": "workspace:*",
    "@types/node": "=24",
    "eslint": "9.39.4",
    "npm-run-all2": "8.0.4",
    "prettier": "3.8.1",
    "tsdown": "0.18.2",
    "tsx": "4.21.0",
    "typescript": "5.9.3",
    "vite": "7.3.1",
    "vitest": "4.1.0"
  },
  "browserslist": [
    "extends @os/browserslist-config"
  ],
  "prettier": "@os/prettier-config"
}
ENDJSON

# ---------------------------------------------------------------------------
# tsconfig.json
# ---------------------------------------------------------------------------
cat > "$PKG_DIR/tsconfig.json" << 'ENDJSON'
{
  "extends": "@os/tsconfig/lib.json"
}
ENDJSON

# ---------------------------------------------------------------------------
# tsdown.config.ts
# ---------------------------------------------------------------------------
cat > "$PKG_DIR/tsdown.config.ts" << 'ENDTS'
// import

import {config} from '@os/tsdown-config';

// export

export default config;
ENDTS

# ---------------------------------------------------------------------------
# vitest.config.ts
# ---------------------------------------------------------------------------
cat > "$PKG_DIR/vitest.config.ts" << 'ENDTS'
// import

import {config} from '@os/vite-config';

// export

export default config;
ENDTS

# ---------------------------------------------------------------------------
# eslint.config.ts
# ---------------------------------------------------------------------------
cat > "$PKG_DIR/eslint.config.ts" << 'ENDTS'
import config from '@os/eslint-config';

export default config;
ENDTS

# ---------------------------------------------------------------------------
# src/index.ts — public API barrel
# ---------------------------------------------------------------------------
apply_template "$PKG_DIR/src/index.ts" << 'ENDTS'
// @os/provider-__NAME__ — __PASCAL__ adapter for @os/provider.
// Generated by new-provider.sh — implement each module.

export {__PASCAL__Model, create__PASCAL__Model, resolveConfig} from './__PASCAL__Model';

/** Create a __PASCAL__ provider from resolved config. */
export {createProvider} from './createProvider';
ENDTS

# ---------------------------------------------------------------------------
# src/${PASCAL}Model.ts — TextModel implementation skeleton
# ---------------------------------------------------------------------------
apply_template "$PKG_DIR/src/${PASCAL}Model.ts" << 'ENDTS'
// __PASCAL__ adapter — implements TextModel via the __PASCAL__ API.
// Generated by new-provider.sh — implement each method.

import type {
  CredentialSupplier,
  ProviderConfig,
  ProviderStreamEvent,
  TextModel,
  TextModelDefaults,
  TextModelInvokeResult,
  TextModelRequest,
  TextModelStreamResult,
} from '@os/provider/types';

import {createTextModelStreamResult, doFetch, doStreamFetch, mergeDefaults} from '@os/provider';

import {classifyError, classifyNetworkError} from './errors';
import {to__PASCAL__Messages} from './messages';
import {parseResponse} from './response';
import {parse__PASCAL__Stream} from './streaming';

const DEFAULT_BASE_URL = 'https://api.example.com'; // TODO: Set correct base URL
const PROVIDER = '__NAME__';

interface AdapterConfig {
  credentials: CredentialSupplier;
  baseUrl: string;
}

/**
 * TextModel backed by the __PASCAL__ API.
 * @see create__PASCAL__Model
 */
export class __PASCAL__Model implements TextModel {
  readonly providerName: string = PROVIDER;
  readonly modelName: string;
  readonly #config: AdapterConfig;
  readonly #defaults: TextModelDefaults | undefined;

  constructor(modelName: string, config: AdapterConfig, defaults?: TextModelDefaults) {
    this.modelName = modelName;
    this.#config = config;
    this.#defaults = defaults;
  }

  async invoke(request: TextModelRequest): Promise<TextModelInvokeResult> {
    const merged = this.#defaults ? mergeDefaults(this.#defaults, request) : request;
    const body = buildRequestBody(this.modelName, merged);
    const headers = await authHeaders(this.#config);
    const response = await doFetch(
      {url: `${this.#config.baseUrl}/v1/chat`, headers, body, signal: merged.options?.signal},
      classifyNetworkError,
      classifyError,
    );

    return parseResponse(response as Record<string, unknown>, this.modelName);
  }

  async stream(request: TextModelRequest): Promise<TextModelStreamResult> {
    const merged = this.#defaults ? mergeDefaults(this.#defaults, request) : request;
    const body = buildRequestBody(this.modelName, merged, true);
    const headers = await authHeaders(this.#config);
    const rawStream = await doStreamFetch(
      {url: `${this.#config.baseUrl}/v1/chat`, headers, body, signal: merged.options?.signal},
      classifyNetworkError,
      classifyError,
      PROVIDER,
    );

    const streamGen = parse__PASCAL__Stream(rawStream, this.modelName);

    const wrappedStream = (async function *streamEvents(): AsyncGenerator<ProviderStreamEvent, TextModelInvokeResult, void> {
      let iterResult = await streamGen.next();

      while (!iterResult.done) {
        yield iterResult.value;
        iterResult = await streamGen.next();
      }

      return iterResult.value;
    }());

    return createTextModelStreamResult(wrappedStream);
  }
}

/** Create a TextModel backed by the __PASCAL__ API. */
export function create__PASCAL__Model(modelName: string, config: AdapterConfig, defaults?: TextModelDefaults): TextModel {
  return new __PASCAL__Model(modelName, config, defaults);
}

/** Create a __PASCAL__ adapter config from a ProviderConfig. */
export function resolveConfig(config: ProviderConfig): AdapterConfig {
  return {
    credentials: config.credentials,
    baseUrl: config.baseUrl ?? DEFAULT_BASE_URL,
  };
}

// --- Internal ---

async function authHeaders(config: AdapterConfig): Promise<Record<string, string>> {
  const apiKey = await config.credentials.resolve();

  return {
    authorization: `Bearer ${apiKey}`,
    'content-type': 'application/json',
  };
}

function buildRequestBody(
  modelName: string,
  request: TextModelRequest,
  stream?: boolean,
): Record<string, unknown> {
  const messages = to__PASCAL__Messages(request);

  const body: Record<string, unknown> = {
    model: modelName,
    messages,
  };

  if (stream) {
    body['stream'] = true;
  }

  if (request.options?.maxTokens !== undefined) {
    body['max_tokens'] = request.options.maxTokens;
  }

  if (request.options?.temperature !== undefined) {
    body['temperature'] = request.options.temperature;
  }

  // TODO: Map remaining request options to __PASCAL__ wire format

  return body;
}
ENDTS

# ---------------------------------------------------------------------------
# src/createProvider.ts — provider factory
# ---------------------------------------------------------------------------
apply_template "$PKG_DIR/src/createProvider.ts" << 'ENDTS'
// __PASCAL__ provider factory.

import type {Provider, ProviderConfig, ProviderFactory, TextModelDefaults} from '@os/provider/types';

import {create__PASCAL__Model, resolveConfig} from './__PASCAL__Model';

/**
 * Create a __PASCAL__ provider from resolved config.
 * @param config - Resolved provider configuration (credentials supplier, base URL, etc.)
 * @returns A configured __PASCAL__ provider.
 */
export const createProvider: ProviderFactory = (config: ProviderConfig): Provider => {
  const adapterConfig = resolveConfig(config);

  return {
    providerName: '__NAME__',
    textModel(modelName: string, defaults?: TextModelDefaults) {
      return create__PASCAL__Model(modelName, adapterConfig, defaults);
    },
  };
};
ENDTS

# ---------------------------------------------------------------------------
# src/messages.ts — content part translation with exhaustive switch
# ---------------------------------------------------------------------------
apply_template "$PKG_DIR/src/messages.ts" << 'ENDTS'
// Translate OpenSpike Message[] + systemPrompt to __PASCAL__ wire format.
// Generated by new-provider.sh — implement each case.

import type {ContentPart, ModelWarning, TextModelRequest} from '@os/provider/types';

// TODO: Define wire types for __PASCAL__

/** Convert a TextModelRequest to __PASCAL__ messages array. */
export function to__PASCAL__Messages(request: TextModelRequest, warnings: ModelWarning[] = []): unknown[] {
  const messages: unknown[] = [];

  if (request.systemPrompt) {
    messages.push({role: 'system', content: request.systemPrompt});
  }

  for (const msg of request.messages) {
    for (const part of msg.content) {
      messages.push(translateContentPart(part, warnings));
    }
  }

  return messages;
}

/** Translate a ContentPart to __PASCAL__ wire format. */
function translateContentPart(
  part: ContentPart,
  warnings: ModelWarning[],
): unknown {
  switch (part.type) {
    case 'text': {
      // CONTRACT: REQ-01 TextPart — translate to provider text format
      void warnings;
      throw new Error('Not implemented: text');
    }

    case 'reasoning': {
      // CONTRACT: REQ-11 ReasoningPart — preserve signature in providerMeta on round-trip
      void warnings;
      throw new Error('Not implemented: reasoning');
    }

    case 'media:file': {
      // CONTRACT: REQ-01 FilePart — translate or emit placeholder + T2 warning
      void warnings;
      throw new Error('Not implemented: media:file');
    }

    case 'media:image': {
      // CONTRACT: REQ-01 ImagePart — read providerMeta.{provider}.detail if applicable
      void warnings;
      throw new Error('Not implemented: media:image');
    }

    case 'media:audio': {
      // CONTRACT: REQ-01 AudioPart — translate or emit placeholder + T2 warning
      void warnings;
      throw new Error('Not implemented: media:audio');
    }

    case 'media:video': {
      // CONTRACT: REQ-01 VideoPart — no provider supports inline video; placeholder + T2 warning
      void warnings;
      throw new Error('Not implemented: media:video');
    }

    case 'tool:call': {
      // CONTRACT: REQ-03 ToolCallPart — re-emit in provider tool call format
      void warnings;
      throw new Error('Not implemented: tool:call');
    }

    case 'tool:exec': {
      // CONTRACT: REQ-05/06 ToolExecPart — all 6 output types; isError MUST be transmitted
      void warnings;
      throw new Error('Not implemented: tool:exec');
    }

    case 'source': {
      // CONTRACT: REQ-08 SourcePart — drop or convert to text (request-side only)
      void warnings;
      throw new Error('Not implemented: source');
    }

    case 'unknown': {
      // CONTRACT: REQ-01 UnknownPart — re-emit raw wire data if providerName matches
      void warnings;
      throw new Error('Not implemented: unknown');
    }

    default: {
      // Exhaustive check — TypeScript error if new ContentPart variant not handled
      const _exhaustive: never = part;
      throw new Error(`Unhandled content part: ${(_exhaustive as ContentPart).type}`);
    }
  }
}
ENDTS

# ---------------------------------------------------------------------------
# src/response.ts — wire response parsing
# ---------------------------------------------------------------------------
apply_template "$PKG_DIR/src/response.ts" << 'ENDTS'
// Parse __PASCAL__ API responses into OpenSpike TextModelInvokeResult.
// Generated by new-provider.sh — implement parsing logic.

import type {ContentPart, FinishReason, TextModelInvokeResult, TokenUsage} from '@os/provider/types';

// TODO: Define __PASCAL__ response wire types

/** Parse a __PASCAL__ response body into a TextModelInvokeResult. */
export function parseResponse(body: Record<string, unknown>, modelName: string): TextModelInvokeResult {
  void body;
  const content: ContentPart[] = [];

  // TODO: Parse response body into content parts

  return {
    providerName: '__NAME__',
    modelName,
    content,
    usage: parseUsage(undefined),
    finishReason: parseFinishReason(undefined),
  };
}

/** Parse __PASCAL__ usage into TokenUsage. */
export function parseUsage(usage: unknown): TokenUsage {
  void usage;

  // TODO: Parse provider-specific usage format
  return {
    input: {total: 0},
    output: {total: 0},
  };
}

/** Map __PASCAL__ finish reason to unified FinishReason. */
export function parseFinishReason(raw: string | null | undefined): FinishReason {
  if (!raw) {
    return {unified: 'stop', raw: raw ?? 'stop'};
  }

  // TODO: Map provider-specific finish reasons
  switch (raw) {
    case 'stop': {
      return {unified: 'stop', raw};
    }

    case 'length': {
      return {unified: 'length', raw};
    }

    case 'tool_calls': {
      return {unified: 'tool-calls', raw};
    }

    default: {
      return {unified: 'other', raw};
    }
  }
}
ENDTS

# ---------------------------------------------------------------------------
# src/streaming.ts — SSE stream parsing
# ---------------------------------------------------------------------------
apply_template "$PKG_DIR/src/streaming.ts" << 'ENDTS'
// Parse __PASCAL__ SSE streaming events into ProviderStreamEvent values.
// Generated by new-provider.sh — implement streaming logic.

import type {ContentPart, ProviderStreamEvent, TextModelInvokeResult} from '@os/provider/types';

import {parseSseStream, ProviderError} from '@os/provider';

import {parseFinishReason, parseUsage} from './response';

// TODO: Define __PASCAL__ streaming wire types

/** Parse an SSE byte stream from __PASCAL__ into ProviderStreamEvent values. */
export async function *parse__PASCAL__Stream(
  stream: ReadableStream<Uint8Array>,
  modelName: string,
): AsyncGenerator<ProviderStreamEvent, TextModelInvokeResult> {
  const content: ContentPart[] = [];
  let seq = 0;

  for await (const sseEvent of parseSseStream(stream)) {
    let chunk: Record<string, unknown> | undefined = undefined;

    try {
      chunk = JSON.parse(sseEvent.data) as Record<string, unknown>;
    } catch (err) {
      throw new ProviderError('SSE chunk parse failed', {
        provider: '__NAME__',
        cause: err instanceof Error ? err : undefined,
      });
    }

    // TODO: Handle each event type and yield ProviderStreamEvent values
    void chunk;
    void seq;
  }

  return {
    providerName: '__NAME__',
    modelName,
    content: [...content],
    usage: parseUsage(undefined),
    finishReason: parseFinishReason(undefined),
  };
}
ENDTS

# ---------------------------------------------------------------------------
# src/errors.ts — error classification
# ---------------------------------------------------------------------------
apply_template "$PKG_DIR/src/errors.ts" << 'ENDTS'
// Classify __PASCAL__ HTTP errors into typed ProviderError.
// Generated by new-provider.sh — customize error parsing for the provider.

import type {ErrorType} from '@os/errors';

import {ErrorTypes, ProviderError, withRetryableError} from '@os/errors';

const PROVIDER = '__NAME__';

/** __PASCAL__ error response body shape. */
interface __PASCAL__ErrorBody {
  message?: string;
  error?: {message?: string};
}

/** Classify an HTTP error response from __PASCAL__ into a ProviderError. */
export function classifyError(status: number, body: unknown): ProviderError {
  const message = parseErrorBody(body) ?? `__PASCAL__ API error (${status})`;
  const type = classifyStatusCode(status);

  const error = new ProviderError(message, {
    type,
    statusCode: status,
    provider: PROVIDER,
    raw: body,
  });

  return isRetryableType(type) ? withRetryableError(error) : error;
}

/** Classify a network/fetch error into a ProviderError. */
export function classifyNetworkError(error: unknown): ProviderError {
  if (error instanceof ProviderError) {
    return error;
  }

  const isAbort = error instanceof DOMException && error.name === 'AbortError';

  if (isAbort) {
    return new ProviderError('Request was aborted', {
      type: ErrorTypes.USER_ABORT,
      provider: PROVIDER,
      cause: error,
    });
  }

  const message = error instanceof Error ? error.message : String(error);
  const isTimeout = (/ETIMEDOUT|timeout/iu).test(message);

  return withRetryableError(new ProviderError(message, {
    type: isTimeout ? ErrorTypes.PROVIDER_TIMEOUT : ErrorTypes.PROVIDER_NETWORK,
    provider: PROVIDER,
    cause: error instanceof Error ? error : undefined,
  }));
}

// --- Internal ---

function classifyStatusCode(status: number): ErrorType {
  switch (status) {
    case 401: // falls through
    case 403: {
      return ErrorTypes.PROVIDER_AUTH;
    }

    case 408: {
      return ErrorTypes.PROVIDER_TIMEOUT;
    }

    case 429: {
      return ErrorTypes.PROVIDER_RATE_LIMIT;
    }

    default: {
      return status >= 500 ? ErrorTypes.PROVIDER_OVERLOAD : ErrorTypes.UNKNOWN;
    }
  }
}

function isRetryableType(type: ErrorType): boolean {
  return (
    type === ErrorTypes.PROVIDER_RATE_LIMIT ||
    type === ErrorTypes.PROVIDER_OVERLOAD ||
    type === ErrorTypes.PROVIDER_TIMEOUT
  );
}

function parseErrorBody(body: unknown): string | undefined {
  if (typeof body !== 'object' || body === null) {
    return undefined;
  }

  const obj = body as __PASCAL__ErrorBody;

  if (typeof obj.message === 'string') {
    return obj.message;
  }

  if (typeof obj.error?.message === 'string') {
    return obj.error.message;
  }

  return undefined;
}
ENDTS

echo "Created @os/provider-${NAME} at $PKG_DIR"
echo ""
echo "Next steps:"
echo "  1. Add 'packages/provider-${NAME}' to pnpm-workspace.yaml"
echo "  2. Run 'pnpm install' to link the new package"
echo "  3. Implement each stubbed module"
echo "  4. Run 'pnpm run check' to validate"
