import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { aliasToolList } from '../aliases/toolNames.ts';
import { composeArtifact, type FrontmatterFields } from '../frontmatter.ts';
import type { CanonicalSources } from '../loadCanonicalSources.ts';

/** Canonical placeholder for "the toolkit's install directory". v0.1 best guess
 *  pending Ch10 eval — OpenCode plugin packages may expand `${OPENCODE_PLUGIN_DIR}`
 *  in shipped content. */
const SKILL_HOME_TOKEN = '__SKILL_HOME__';
const OPENCODE_PLUGIN_DIR = '${OPENCODE_PLUGIN_DIR}';

/** Substitute the toolkit-home placeholder for the OpenCode package layout. */
function subSkillHome(text: string): string {
  return text.split(SKILL_HOME_TOKEN).join(OPENCODE_PLUGIN_DIR);
}

interface PackageMeta {
  name: string;
  version: string;
  description: string;
}

/** A hook compiled into the generated plugin: an event matcher → bash handler. */
interface CompiledHook {
  name: string;
  /** OpenCode tool-execute event the hook binds to (v0.1: only `PreToolUse`). */
  event: string;
  /** Tool names the matcher accepts (`Edit|Write` → `['Edit', 'Write']`). */
  toolNames: string[];
}

function write(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
}

function copyExecutable(from: string, to: string): void {
  mkdirSync(dirname(to), { recursive: true });
  cpSync(from, to);
}

/** OpenCode canonical events map onto its `tool.execute.before` hook; v0.1 only
 *  emits `PreToolUse` (the canonical hook set is all `PreToolUse`). */
function openCodeEventOf(canonicalEvent: string): string {
  if (canonicalEvent === 'PreToolUse') return 'tool.execute.before';
  throw new Error(`opencode emit: unsupported hook event '${canonicalEvent}' (v0.1 supports PreToolUse only)`);
}

/** The generated OpenCode TS plugin. Ships the canonical bash handlers alongside
 *  (`hooks/<name>.sh`) and dispatches each one for the matching tool event,
 *  piping the OpenCode hook payload through stdin and surfacing a deny. */
function renderPluginTs(hooks: CompiledHook[]): string {
  const handlers = hooks
    .map(
      (h) =>
        `  { name: ${JSON.stringify(h.name)}, event: ${JSON.stringify(openCodeEventOf(h.event))}, ` +
        `tools: ${JSON.stringify(h.toolNames)} },`,
    )
    .join('\n');
  return `import { spawnSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Generated by @mikestopcontinues/agent-skills — do not edit by hand. */

const PLUGIN_DIR = dirname(fileURLToPath(import.meta.url));
const HOOKS_DIR = join(PLUGIN_DIR, '..', 'hooks');

interface HookHandler {
  readonly name: string;
  readonly event: string;
  readonly tools: readonly string[];
}

const HANDLERS: readonly HookHandler[] = [
${handlers}
];

interface ToolExecuteBeforeInput {
  readonly tool: string;
}

interface ToolExecuteBeforeOutput {
  args: Record<string, unknown>;
}

function runHandler(name: string, payload: unknown): void {
  const script = join(HOOKS_DIR, name + '.sh');
  const result = spawnSync('bash', [script], { input: JSON.stringify(payload), encoding: 'utf8' });
  if (result.status !== 0) {
    const reason = (result.stdout || result.stderr || '').trim();
    throw new Error(reason.length > 0 ? reason : 'agent-skills hook ' + name + ' denied the operation');
  }
}

function matches(handler: HookHandler, tool: string): boolean {
  return handler.tools.length === 0 || handler.tools.includes(tool);
}

const plugin = async () => ({
  'tool.execute.before': async (input: ToolExecuteBeforeInput, output: ToolExecuteBeforeOutput): Promise<void> => {
    for (const handler of HANDLERS) {
      if (handler.event !== 'tool.execute.before') continue;
      if (!matches(handler, input.tool)) continue;
      runHandler(handler.name, { tool: input.tool, args: output.args });
    }
  },
});

export default plugin;
`;
}

/**
 * Emit the OpenCode npm-package bundle to `outDir`:
 *
 *   <outDir>/
 *     package.json
 *     src/plugin.ts                     (generated plugin entry)
 *     hooks/<name>.sh                   (canonical bash handlers, byte-identical)
 *     skills/<name>/SKILL.md            (+ extras: focuses/, chapter.md, …)
 *     agents/<name>.md
 *     scripts/<name>                    (yolo, doc-check-links.sh)
 *     docs/AGENTS.md                    (project context, if present)
 *
 * Consumers add the package to `opencode.json`'s `cfg.plugin`. `__SKILL_HOME__`
 * in skill bodies / skill extras / agent prompts is substituted to
 * `${OPENCODE_PLUGIN_DIR}`. The generated `src/plugin.ts` locates `hooks/<name>.sh`
 * relative to its own module URL at runtime.
 */
export function emitOpenCode(sources: CanonicalSources, outDir: string, meta: PackageMeta): void {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  // package.json (minimal).
  write(
    join(outDir, 'package.json'),
    JSON.stringify(
      { name: meta.name, version: meta.version, description: meta.description, type: 'module', main: 'src/plugin.ts' },
      null,
      2,
    ) + '\n',
  );

  // Hooks — ship the canonical bash handlers; the generated plugin spawns them.
  const compiled: CompiledHook[] = [];
  for (const { hook, handlerPath } of sources.hooks) {
    const def = hook.def;
    write(join(outDir, 'hooks', `${def.name}.sh`), readFileSync(handlerPath, 'utf8'));
    compiled.push({ name: def.name, event: def.event, toolNames: def.matcher === '' ? [] : def.matcher.split('|') });
  }
  write(join(outDir, 'src', 'plugin.ts'), renderPluginTs(compiled));

  // Skills — OpenCode skill frontmatter is `name` + `description` only (no `tools` line).
  for (const { skill, bodyPath, extras } of sources.skills) {
    const def = skill.def;
    const fields: FrontmatterFields = { name: def.name, description: def.description };
    write(join(outDir, 'skills', def.name, 'SKILL.md'), composeArtifact(fields, subSkillHome(readFileSync(bodyPath, 'utf8'))));
    for (const [rel, abs] of extras.files) write(join(outDir, 'skills', def.name, rel), subSkillHome(readFileSync(abs, 'utf8')));
  }

  // Agents (personas) — OpenCode subagent `.md`: frontmatter (mode/model/tools),
  // body = the persona prompt.
  for (const { agent, promptPath } of sources.agents) {
    const def = agent.def;
    const fields: FrontmatterFields = { mode: 'subagent' };
    if (def.model !== undefined) fields['model'] = def.model;
    fields['tools'] = aliasToolList('opencode', def.tools).join(', ');
    write(join(outDir, 'agents', `${def.name}.md`), composeArtifact(fields, subSkillHome(readFileSync(promptPath, 'utf8'))));
  }

  // Shipped scripts.
  for (const [name, abs] of sources.scripts) copyExecutable(abs, join(outDir, 'scripts', name));

  // Project context (if present): docs/AGENTS.md.
  if (sources.projectContext) {
    write(join(outDir, 'docs', sources.projectContext.def.harnessFilenames.opencode), sources.projectContext.def.content);
  }
}

/** Convenience: emit using the agent-skills package's name/version. */
export function emitOpenCodeFromPackage(sources: CanonicalSources, outDir: string): void {
  const pkg = JSON.parse(readFileSync(resolve(import.meta.dirname, '../../../package.json'), 'utf8')) as {
    name: string;
    version: string;
    description: string;
  };
  emitOpenCode(sources, outDir, pkg);
}
