import { spawnSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Generated by @mikestopcontinues/agent-skills — do not edit by hand. */

const PLUGIN_DIR = dirname(fileURLToPath(import.meta.url));
const HOOKS_DIR = join(PLUGIN_DIR, '..', 'hooks');

interface HookHandler {
  readonly name: string;
  readonly event: string;
  readonly tools: readonly string[];
}

const HANDLERS: readonly HookHandler[] = [
  { name: "block-main-edits", event: "tool.execute.before", tools: ["Bash"] },
  { name: "pre-bash-doc", event: "tool.execute.before", tools: ["Bash"] },
  { name: "pre-commit-gate", event: "tool.execute.before", tools: ["Bash"] },
  { name: "pre-write-doc", event: "tool.execute.before", tools: ["Write"] },
  { name: "verify-worktree-path", event: "tool.execute.before", tools: ["Edit","Write"] },
];

interface ToolExecuteBeforeInput {
  readonly tool: string;
}

interface ToolExecuteBeforeOutput {
  args: Record<string, unknown>;
}

function runHandler(name: string, payload: unknown): void {
  const script = join(HOOKS_DIR, name + '.sh');
  const result = spawnSync('bash', [script], { input: JSON.stringify(payload), encoding: 'utf8' });
  if (result.status !== 0) {
    const reason = (result.stdout || result.stderr || '').trim();
    throw new Error(reason.length > 0 ? reason : 'agent-skills hook ' + name + ' denied the operation');
  }
}

function matches(handler: HookHandler, tool: string): boolean {
  return handler.tools.length === 0 || handler.tools.includes(tool);
}

const plugin = async () => ({
  'tool.execute.before': async (input: ToolExecuteBeforeInput, output: ToolExecuteBeforeOutput): Promise<void> => {
    for (const handler of HANDLERS) {
      if (handler.event !== 'tool.execute.before') continue;
      if (!matches(handler, input.tool)) continue;
      runHandler(handler.name, { tool: input.tool, args: output.args });
    }
  },
});

export default plugin;
